const constants = {
  LOAD_DATA_SERVER: 'LOAD_DATA_SERVER',
  LOAD_DATA_ROLE: 'LOAD_DATA_ROLE',
  LOAD_DATA_FROM_SEND: 'LOAD_DATA_FROM_SEND',
  LOAD_DATA_FROM_RECEIVE: 'LOAD_DATA_FROM_RECEIVE',
  ADD_ONLINE_SERVER: 'ADD_ONLINE_SERVER',
  ADD_OFFLINE_SERVER: 'ADD_OFFLINE_SERVER',
  DELETE_ONLINE_SERVER: 'DELETE_ONLINE_SERVER',
  DELETE_OFFLINE_SERVER: 'DELETE_OFFLINE_SERVER',
  ADD_SOCKET: 'ADD_SOCKET',
  UPDATE_SERVER_CHATTING: 'UPDATE_SERVER_CHATTING',
  UPDATE_REPLY_STATUS: 'UPDATE_REPLY_STATUS',
  LOAD_REPLY: 'LOAD_REPLY',
  UPDATE_FORM_STATUS: 'UPDATE_FORM_STATUS',
  LOAD_FORM: 'LOAD_FORM',
  UPDATE_ROLE_CHATTING: 'UPDATE_ROLE_CHATTING',
  UPDATE_FILTER: 'UPDATE_FILTER',
  UPDATE_LIMIT_MESSAGE: 'UPDATE_LIMIT_MESSAGE'
};

export default constants;
